# Generated by Django 2.2.4 on 2019-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adulisapp', '0002_auto_20190913_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
